#ifndef INCLUDE_CONFIG_H
#define INCLUDE_CONFIG_H

#define PROJECT_NAME "Kedge"
#define PROJECT_VER  "0.0.2"
#define PROJECT_VER_MAJOR "0"
#define PROJECT_VER_MINOR "0"
#define PTOJECT_VER_PATCH "2"

#define SERVER_SIGNATURE "Kedge/0.0.2"

#define ENV_KEDGE_WEB_UI "KEDGE_WEB_UI"

#endif // INCLUDE_CONFIG_H
