#ifndef INCLUDE_CONFIG
#define INCLUDE_CONFIG

#define PROJECT_NAME "Kedge"
#define PROJECT_VER  "0.0.2"
#define PROJECT_VER_MAJOR "0"
#define PROJECT_VER_MINOR "0"
#define PTOJECT_VER_PATCH "2"

#endif // INCLUDE_CONFIG
